{% set version = "1.1-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gnm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gnm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gnm/gnm_{{ version }}.tar.gz
  sha256: d22962963545b3aa1de3a563c5ae4b8038b09c7a9a96185708b35c4d032b1c37

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-nnet
    - r-qvcalc >=0.8_3
    - r-relimp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass
    - r-matrix
    - r-nnet
    - r-qvcalc >=0.8_3
    - r-relimp

test:
  commands:
    - $R -e "library('gnm')"           # [not win]
    - "\"%R%\" -e \"library('gnm')\""  # [win]

about:
  home: https://github.com/hturner/gnm
  license: GPL-2.0-or-later
  summary: Functions to specify and fit generalized nonlinear models, including models with multiplicative interaction terms such as the UNIDIFF model from sociology and the AMMI model from crop science, and many others.  Over-parameterized representations of models are used throughout; functions are provided for inference
    on estimable parameter combinations, as well as standard methods for diagnostics etc.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gnm
# Title: Generalized Nonlinear Models
# Version: 1.1-1
# Authors@R: c(person("Heather", "Turner", email = "ht@heatherturner.net", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1256-3375")), person("David", "Firth", role = "aut", comment = c(ORCID = "0000-0003-0302-2312")), person("Brian", "Ripley", role = "ctb"), person("Bill", "Venables", role = "ctb"), person(c("Douglas", "M."), "Bates", role = "ctb"), person("Martin", "Maechler", role = "ctb", comment = c(ORCID = "0000-0002-8685-9910")))
# Description: Functions to specify and fit generalized nonlinear models, including models with multiplicative interaction terms such as the UNIDIFF model from sociology and the AMMI model from crop science, and many others.  Over-parameterized representations of models are used throughout; functions are provided for inference on estimable parameter combinations, as well as standard methods for diagnostics etc.
# URL: https://github.com/hturner/gnm
# BugReports: https://github.com/hturner/gnm/issues
# License: GPL-2 | GPL-3
# Depends: R (>= 3.0.0)
# Imports: graphics, grDevices, MASS, Matrix, methods, nnet, qvcalc (>= 0.8-3), relimp, stats, utils
# Suggests: testthat, vcdExtra
# LazyData: yes
# Language: en-GB
# NeedsCompilation: yes
# Packaged: 2020-02-02 19:31:05 UTC; hturner
# Author: Heather Turner [aut, cre] (<https://orcid.org/0000-0002-1256-3375>), David Firth [aut] (<https://orcid.org/0000-0003-0302-2312>), Brian Ripley [ctb], Bill Venables [ctb], Douglas M. Bates [ctb], Martin Maechler [ctb] (<https://orcid.org/0000-0002-8685-9910>)
# Maintainer: Heather Turner <ht@heatherturner.net>
# Repository: CRAN
# Date/Publication: 2020-02-03 14:20:02 UTC
