{% set version = '1.1-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gnm
  version: {{ version|replace("-", "_") }}

source:
  fn: gnm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gnm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gnm/gnm_{{ version }}.tar.gz
  sha256: b43a91fbe51848a414858ece413d2886d2fbbed4c2d88da0243c350275e7a705

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-matrix
    - r-nnet
    - r-qvcalc >=0.8_3
    - r-relimp
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-matrix
    - r-nnet
    - r-qvcalc >=0.8_3
    - r-relimp

test:
  commands:
    - $R -e "library('gnm')"           # [not win]
    - "\"%R%\" -e \"library('gnm')\""  # [win]

about:
  home: https://github.com/hturner/gnm
  license: GPL-2 | GPL-3
  summary: Functions to specify and fit generalized nonlinear models, including models with multiplicative
    interaction terms such as the UNIDIFF model from sociology and the AMMI model from
    crop science, and many others.  Over-parameterized representations of models are
    used throughout; functions are provided for inference on estimable parameter combinations,
    as well as standard methods for diagnostics etc.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
