# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DkzKRtKAoXfHtCyxE4EnKz7NsIr2eAnEVCWhMj1FgFgNtDlYzj6iWXEyoflg1kK1akaMm1DooHJ5qUQPwY+1/H+sMTfUurwV5yOM5POZf5t1dJ53oVpNTG0dE7PQGZAXGNS3OfkRFujg8qfs6K3CtqzPlqKKeKCLXOsfyn0y2m2Egj3yJMoR8OpRtKjUlt3RKp+E2QGh5XsjAk84Z9/SskRPPxwXB3trwJX5FZMTIErNdK0kz5zk7Tp7LdjLyD/paTIpK5tRTqBn8bTMw40EO3h1VnNJWvxn0PCHmoHjGnLogGMvANw2Vd7lBVTJCp0DnubPadJGeE27ulJEINJbIgyW+GoCXaLsEJeON287G1iRoyzVPXgtS1j29SiHXkBv7sFv8WHXYfNCKHZqDYF0fnJfu92oyyvnA1sK7wEwGwrDeXOE7vflePhkjUOxAJI41a/tKIooilZxjSUU8xy7O3uySURwPvCcDctQ+uoViht2T9VRe4AQZ34FkLYtfj1wKy02t0H3jpiM6uvGuSvlRbrlZfnBh0dpYMXcUGaCHvlhPGXsOwvoDfTfebeDTjB8GLMJbFGNbAMUj0nHcjVx6k542Ln/72bShDwe461RKGEU6IZxdE7qDCKXpYujxFz8vhoa8w774z3E6E/rSd8jxTBoB5aMqtFZZJofyLWQfG8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
