travis:
  secure:
    BINSTAR_TOKEN: e6kvs9HJKO1dB5Iau/rkOxvzpRiqeA+ln/u1uQBYgcSW0f/UrpaiN43Lv+Ec/LAOJrLu5ee2X3rnMD6YGiuRU3QX5t2b3DedaEMJ0IWOhTYylYOuIU29kNjhiOgQp/Umx4zVgjdttsyf/HMZQyi0SgO7apk4SMypP71CubHFQoc9rJRvuSf1LndcQIAdZOeDFIYrkvVnh+HTtSZRQfP9suF5H8a7jk9TVqFfg8CpehMrZLzcYe4qaqCStwdXDGzND+qQuwOT5CeF/F+Tbv48h5h71oko7EWzIDYmdcBaTKugUCdvstWPqHipPSUIYFX/JtDiH3+Mc6KQlpEmG0SehLneZw3nmFmWXjgzO9PW2UVBS6mChHb59ld0geqycIsI1CSwIvr1PVtPLp1gEQJozVPBOcP9yugKZifymOV18ryUkIvHCfhrrkzkLT99D+U7WDwlIQrkTpXuwM8X5SHc+6vuPVr2XeUuLK4ORtZ4+4PR7+XkEm5ljMnQpTzGco3cyM9ZU3l98VBVlt6xm3G92yIjMtSiCz14bmtqg99cpQTG5rA5hYZhcEzUnn6oqoBUG2lGgkf97Pg6pZf2QhMYIXdZnuTtTcxZTB3a5C4zO2iXOPMnLWMiCLZjNPJ9Bu28sTwZCuWFrkm8m0YrE5SOmXV16ymmV9tvGXjrbqp5/8w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
