travis:
  secure:
    BINSTAR_TOKEN: bflmgllT+IDqAHrKz4Dx8p1b4TZGUtAAYEwgObv1yKtf73+oG2s+BBjROiZJDPc7lT0ZG0Wvnm4KW55lUvRw1mquJ7dRDBbB1STV/yWUnVYDDHZSYv8Bx0203Dkt0ofgP5S9nXwakm3XoDX1lbIo0N6+x8MEYOb8NyEHspt5LWUA2AzcTMVDVvo6gcRV6SxHDZiLjoNv/H579tLjNsrewxRZfLV5YSfTuZV92y14cU+5elTcl5z5SIq6R1MPol9Ek+ikA01pbE021wJ6/8d2lIAV7NBl8zMsjB1VctSupmHXrP3RqPZ1Qn2PdURo8eJx9OYXRifNec0ONB3rt6NwwE5v7Gnc2gKs82YEsdOts0wQwTlt8oEwakP2uWifXgUf+r4AvpePM/dlYLYrP3t5tGY5qG36DlwNOi15LCYdaY6WX7JU9cjl32bXtRge5Fb1A/JslJQQFLnjgvDwdis0ASL3y4RJj5hWPce+3qthhrj/4hNJ+Nq8Ci65z4093dbtEA8yjLyzC1Q3fr1jRnuIZ5cR5Y7DfqGG7v9MfPVX7P2k1mMb4CSRFNMIXTAnKqB/McYS5JoBpHWGn9JGwRBFPVlwlhGlS0L6k9uNdXZixyKcu6sEFSUUl3T0SboyI2b2abKluRPrk0d2iutc2hUZpcXWrBre3gnj9r4qSLHSQgo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
