travis:
  secure:
    BINSTAR_TOKEN: B9nmrLRWkr1r2njXzw6lCJkE4YGSXdvKPErG+3YF5/sVgsKwcREE2pCcZkMJ7wLwTBVBNkI0fWW7E1UZVz2Rdb2TlF8sJxzvvn5Ob4r+ev0rfIgugzkUrv/Wtsuk6/B+9mOuTM3WHodT5wD9OJprx5G8IQ5FlamYac/G3G1IIiDnA3Gcc5Fl5QqWMM8QL8T+WMaaudWom8l5T6V8WfsyufvrFmWQn2S7nxi5Zgb9ytuzg/egCwW3KctoESa/jMso7xj0zAvA9A7qNeTI9VDP32l0ToWLWib5Wl0MS54MpZvGlGhbhDnxW8SExlDAZyV1gEz6FTX2bQCcZrhPWT2duYw2BdJRjgYcaaZsrFjyLzxXOBKl8rP9CeeGHkKVgJN5RY2TZM80F7rJoG0zKDLrj0YG0+YeO3qEHXsnJrMab96l6sFS+J4C7o+6AY03MkREweiiHkGlHSqfgOw34zCQpLIzbLQKhAEBT+oRIj/++xiIRSS+/wFyo2sWH5ITqYUoZuhB8u9wrgfsAK7D+mv892Siygu6HHxixFq7pNYVeUMpHWJBK+i69Q5AO4RnBS5O1V3CdY5GrmV7lqPwNpr1RGGu92mHDsKJN9yppWtYGnyaaKqg+5899Hc8lcCsDySga54115kZyw1nA/B2DT7Z/X2xWT6NDya88Ew5urcvuv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
