travis:
  secure:
    BINSTAR_TOKEN: HGMeVX9r9gES/J4TwWgN/3RcAD3xymmEbGrfGOevSQLJ1d95TpZPTmRSCvarmmKbX/UNeKuaVoFTr31HmMWbJN23JtOt08ef6gSnzDVbH5iRSfbXWn411+jiwn3M4nqRgXbw7ol/uBKZBt0VvSVXNeWqQDFtBjlx3tBg375OvKM65oIotaAjDlbFH5Cksa+GwUgeG92Jk7N57E5I0DeyC/qibYLJ8tXMIn8IRExNHO8Gny7SfjSuFvqCxqXPb66YfyBwZMXq2llKqwwzQrIFEmS09uWqiEVaUj7uToa/o0SjADnbXbItvtDSWw0zQj/NgEjU5rPmsDUpY5HpUMSfU8ZMdzytxIzgcHAN7ibomZNxo9GVc1sE67dSc31wxeXukjWjdWIxet7OIw60dPVzotfMG+KDE1TQcYPvfzb5H6AkS9N30NHc+8Yc7ifJF8ZR4OHqUPYNd8+S/9GQCZ9PSNM/zma0N/YBiEzgP4rUgj3ueoP8c18Fw8lJheGkcIIe8TVPLVQN0Dh+7iKq6sPspo3eVzddWFOG5kXgQ3MfrjXKXTTl6sUYMxTJukdVGxiKUk8cEJwrSesarJRu76WeJKJQD3s4XRcpAhfcodxiB4bLRVdVNU4Buv8wyNkz3K090mB0SHBX1YrN0BWLIuaPQmFZsEH7sgCOcvKjQfUbEoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
