travis:
  secure:
    BINSTAR_TOKEN: DkzKRtKAoXfHtCyxE4EnKz7NsIr2eAnEVCWhMj1FgFgNtDlYzj6iWXEyoflg1kK1akaMm1DooHJ5qUQPwY+1/H+sMTfUurwV5yOM5POZf5t1dJ53oVpNTG0dE7PQGZAXGNS3OfkRFujg8qfs6K3CtqzPlqKKeKCLXOsfyn0y2m2Egj3yJMoR8OpRtKjUlt3RKp+E2QGh5XsjAk84Z9/SskRPPxwXB3trwJX5FZMTIErNdK0kz5zk7Tp7LdjLyD/paTIpK5tRTqBn8bTMw40EO3h1VnNJWvxn0PCHmoHjGnLogGMvANw2Vd7lBVTJCp0DnubPadJGeE27ulJEINJbIgyW+GoCXaLsEJeON287G1iRoyzVPXgtS1j29SiHXkBv7sFv8WHXYfNCKHZqDYF0fnJfu92oyyvnA1sK7wEwGwrDeXOE7vflePhkjUOxAJI41a/tKIooilZxjSUU8xy7O3uySURwPvCcDctQ+uoViht2T9VRe4AQZ34FkLYtfj1wKy02t0H3jpiM6uvGuSvlRbrlZfnBh0dpYMXcUGaCHvlhPGXsOwvoDfTfebeDTjB8GLMJbFGNbAMUj0nHcjVx6k542Ln/72bShDwe461RKGEU6IZxdE7qDCKXpYujxFz8vhoa8w774z3E6E/rSd8jxTBoB5aMqtFZZJofyLWQfG8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
